"""Node name constants for the Customer Support Resolution Copilot graph."""

CLASSIFY_TICKET = "classify_ticket"
RETRIEVE_POLICY = "retrieve_policy"
CUSTOMER_CONTEXT = "customer_context"
MINIMAL_CUSTOMER_CONTEXT = "minimal_customer_context"
RISK_CHECK = "risk_check"
DRAFT_RESPONSE = "generate_resolution_plan"
GROUNDEDNESS_CHECK = "groundedness_check"
MANUAL_REVIEW_RESPONSE = "manual_review_response"
APPROVAL_GATE = "approval_gate"
AUDIT_LOG = "audit_log"
FINAL_RESPONSE = "final_response"
